import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const read = name => readFileSync(new URL(name, import.meta.url), 'utf8');
const compose = JSON.parse(read('compose.json'));
const overlay = JSON.parse(read('hq.overlay.json'));
const service = compose.services['memex-tls'];
assert.equal(service.user, '1000:1000'); assert.equal(service.read_only, true);
assert.equal(service.ports, undefined); assert.equal(service.privileged, undefined);
assert.equal(service.volumes, undefined); assert.deepEqual(service.cap_drop, ['ALL']);
assert.equal(compose.networks['bridge-tls'].internal, true);
assert.equal(compose.networks['memory-private'].external, true);
assert.equal(overlay.services.hq.ports, undefined);
assert.equal(overlay.services.hq.environment.NODE_EXTRA_CA_CERTS, '/run/memex-ca/ca.crt');
assert.equal(overlay.services.hq.environment.MEMEX_HTTP_READ_HANDLE_FILE, '/run/memex-read/handle');
assert.equal(overlay.services.hq.environment.ORIA_ENABLE_MEMEX_HTTP_READONLY, undefined);
assert.deepEqual(overlay.services.hq.volumes.map(v => v.target).sort(), ['/run/memex-ca/ca.crt', '/run/memex-read']);
assert.ok(overlay.services.hq.volumes.every(v => v.read_only && v.bind.create_host_path === false));
assert.match(read('Dockerfile'), /node@sha256:25330af3531fb5e23318554a0aa911125b6e91b1b777edf7655501d207c067a2/);
assert.doesNotMatch(read('proxy.mjs'), /console\.|process\.env|rejectUnauthorized/);
console.log('Memex TLS static boundary checks passed');
